In [38]:
import numpy as np

In [132]:
dict_x = {}
for x in range(10):
    dict_x[x] = np.random.randint(9,size=(1,10))
dict_x

{0: array([[8, 3, 2, 4, 8, 7, 2, 0, 0, 0]]),
 1: array([[3, 8, 1, 1, 7, 5, 2, 1, 2, 2]]),
 2: array([[5, 6, 0, 3, 3, 3, 3, 2, 2, 2]]),
 3: array([[3, 4, 7, 2, 4, 2, 7, 3, 3, 2]]),
 4: array([[1, 6, 4, 0, 8, 5, 2, 6, 6, 7]]),
 5: array([[7, 6, 7, 8, 8, 3, 5, 7, 7, 3]]),
 6: array([[0, 4, 2, 1, 1, 5, 7, 4, 0, 0]]),
 7: array([[6, 7, 1, 2, 8, 0, 7, 2, 3, 0]]),
 8: array([[8, 0, 3, 6, 0, 8, 8, 2, 0, 1]]),
 9: array([[4, 5, 8, 8, 1, 6, 7, 4, 5, 7]])}

In [151]:
z = np.vstack([v for k,v in dict_x.items()])
print(z)

[[8 3 2 4 8 7 2 0 0 0]
 [3 8 1 1 7 5 2 1 2 2]
 [5 6 0 3 3 3 3 2 2 2]
 [3 4 7 2 4 2 7 3 3 2]
 [1 6 4 0 8 5 2 6 6 7]
 [7 6 7 8 8 3 5 7 7 3]
 [0 4 2 1 1 5 7 4 0 0]
 [6 7 1 2 8 0 7 2 3 0]
 [8 0 3 6 0 8 8 2 0 1]
 [4 5 8 8 1 6 7 4 5 7]]


In [152]:
z.shape

(10, 10)

In [160]:
z[z>3]   # Prints all the numbers greater than 3

array([8, 4, 8, 7, 8, 7, 5, 5, 6, 4, 7, 4, 7, 6, 4, 8, 5, 6, 6, 7, 7, 6,
       7, 8, 8, 5, 7, 7, 4, 5, 7, 4, 6, 7, 8, 7, 8, 6, 8, 8, 4, 5, 8, 8,
       6, 7, 4, 5, 7])

In [161]:
z>3     # Just True if value > 3 else False

array([[ True, False, False,  True,  True,  True, False, False, False,
        False],
       [False,  True, False, False,  True,  True, False, False, False,
        False],
       [ True,  True, False, False, False, False, False, False, False,
        False],
       [False,  True,  True, False,  True, False,  True, False, False,
        False],
       [False,  True,  True, False,  True,  True, False,  True,  True,
         True],
       [ True,  True,  True,  True,  True, False,  True,  True,  True,
        False],
       [False,  True, False, False, False,  True,  True,  True, False,
        False],
       [ True,  True, False, False,  True, False,  True, False, False,
        False],
       [ True, False, False,  True, False,  True,  True, False, False,
        False],
       [ True,  True,  True,  True, False,  True,  True,  True,  True,
         True]])