In [1]:
# Importing numpy and aliasing as np
import numpy as np

In [23]:
#Declaring array 'a'
a = np.array(([1,2,3,4]))

In [24]:
#Print np Object
a

array([1, 2, 3, 4])

In [26]:
#Print np array
print(a)

[1 2 3 4]


In [12]:
#Declare two-dimension array 'b'
b = np.array(([1,2,3,4],[3,4,5,6]))


In [14]:
b

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [15]:
print(b)

[[1 2 3 4]
 [3 4 5 6]]


In [19]:
#Declare a three-Dimensional array 'c'
c = np.array(([[1,2],[3,4]],[[3,4],[5,6]]))

In [20]:
c

array([[[1, 2],
        [3, 4]],

       [[3, 4],
        [5, 6]]])

In [21]:
print(c)

[[[1 2]
  [3 4]]

 [[3 4]
  [5 6]]]
