## Mathematical & Statistical Functions

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])

In [3]:
a+2

array([3, 4, 5, 6])

In [4]:
a+2    # Observe here... to hold the data of previous command.. it has to be copied to itself

array([3, 4, 5, 6])

In [5]:
a-3

array([-2, -1,  0,  1])

In [6]:
a*2

array([2, 4, 6, 8])

In [7]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [8]:
a//2

array([0, 1, 1, 2], dtype=int32)

In [9]:
a%2

array([1, 0, 1, 0], dtype=int32)

In [10]:
import math                          # Just if you want to convert values to ceil instead of floor
print([math.ceil(x) for x in a/2])

[1, 1, 2, 2]


In [11]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [12]:
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128])

In [13]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

### Linear Algebra




In [14]:
a = np.random.randint(5,size=(3,2))
b = np.random.randint(5,10,size = (2,3))
print(a,b,sep='\n\n')

[[3 2]
 [1 0]
 [2 0]]

[[8 5 5]
 [7 9 5]]


In [15]:
a*b  # This is not matrix multiplication this is broad cast there is a method 'matmul' for matrix multiplication as below

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [ ]:
c = np.matmul(a,b)
c

In [ ]:
print(np.linalg.det(c))   # Always careful det is only possible to calculate over square matrices



## Statistical Functions



In [20]:
l = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [21]:
np.min(l)

1

In [23]:
np.max(l)

12

In [24]:
np.min(l,axis = 0)  # Min of each column

array([1, 2, 3, 4])

In [26]:
np.min(l,axis = 1)  # Min of each row

array([1, 5, 9])

In [27]:
np.max(l,axis = 0)  # Max of each column

array([ 9, 10, 11, 12])

In [28]:
np.max(l,axis = 1)  # Max of rach row

array([ 4,  8, 12])

In [29]:
np.sum(l)

78

In [30]:
np.sum(l,axis = 0)

array([15, 18, 21, 24])

In [31]:
np.sum(l,axis = 1)

array([10, 26, 42])

In [33]:
np.average(l),np.average(l,axis = 0),np.average(l,axis = 1)

(6.5, array([5., 6., 7., 8.]), array([ 2.5,  6.5, 10.5]))