In [1]:
import numpy as np

In [2]:
a = np.array(([1,2,3,4]))

In [3]:
a[0] # Returns 1st element

1

In [4]:
a[[1,3]] # Returns 1st and 3rd index elements

array([2, 4])

In [5]:
a[-1] #Returns last element via -ve index

4

In [6]:
a[:] # Returns 0th to last index element (i.e complete array)

array([1, 2, 3, 4])

In [7]:
a[1:3] #Slicing 1st and (n-1) i.e 2nd element

array([2, 3])

In [8]:
b = np.array(([4,5,6,7,8,9,]))

In [9]:
b[::2]

array([4, 6, 8])

In [10]:
b[::-1]  # b[x:y:z] if x,y both are None and z is -ve  -- it will print elements in reverse order

array([9, 8, 7, 6, 5, 4])

In [11]:
b[:3:-1] # b[x:y:z] if x is None and y both are +ve and z is -ve  -- it will print complement of elements in reverse order.. 
#i.e instead of printing [0],[1],[2] it will print [4],[5] in reverse excluding 3 i.e y

array([9, 8])

In [12]:
b[3::-1] # b[x:y:z] if x is +ve and y is none and z is -ve  -- it will print complement of elements in reverse order.. 
#i.e instead of printing [3],[4],[5] it will print [1],[2],[3],[4](Complement of [3],[4],[5]) in reverse excluding 3 i.e x

array([7, 6, 5, 4])

In [13]:
b[-2::-1] # b[x:y:z] if x is -ve and y is none and z is -ve  -- it will print complement of elements in reverse order.. 
#i.e instead of printing [-2] to End(i.e [5])  it will print [-3],[-4],[-5],[-6](Complement of [-1],[-2]) in reverse excluding 3 i.e x

array([8, 7, 6, 5, 4])

In [14]:
b[:-3:-1] # b[x:y:z] if x is none and y is -ve and z is -ve  -- it will print complement of elements in reverse order.. 
#i.e instead of printing Start[0],[-3] it will print [-4],[-5](Complement of [0] to [-3]) in reverse excluding 3 i.e y

array([9, 8])

In [15]:
b[-1:-4:-1]

array([9, 8, 7])

In [16]:
b

array([4, 5, 6, 7, 8, 9])

In [17]:
b[1::-1]

array([5, 4])

### Accessing Multi Dimensional Arrays

In [18]:
c = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])

In [19]:
c

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [20]:
c[0,3]

4

In [21]:
c[1,4]

11

In [22]:
c[1,:]  # This will result entire [1] row and all columns

array([ 7,  8,  9, 10, 11, 12])

In [23]:
c[:,1]  # This will result will entire [1] column in all rows

array([2, 8])

In [26]:
c[[1],[3,4]]  # This will result [1]st row's [3] and [4] columns

array([10, 11])

In [27]:
c[[0,1],[3,4]]  # This is assosciative.. i.e it will select [0]th row [3]rd column element; [1]st row [4]th column element

array([ 4, 11])

In [40]:
c[[0,1],3:5]   # This is not assosciative.. i.e it will select [0]th row 3,4 columns and [1]st row 3,4 columns

array([[ 4,  5],
       [10, 11]])

In [41]:
c[0:2,3:5]    # Alternate way of above expression

array([[ 4,  5],
       [10, 11]])