In [1]:
import numpy as np
from IPython.display import display

In [2]:
file = np.genfromtxt('Datasets/Student.csv',delimiter=',',skip_header=1)  # Here we are skipping 1st line as it contains str

In [3]:
file = file.astype(int)    # Converting the data type of float into int

In [4]:
np.set_printoptions(threshold=np.inf)
display(file)              # Using display of IPython

array([[1, 1, 1, 1, 1, 1],
       [4, 4, 3, 4, 4, 4],
       [2, 1, 3, 4, 1, 1],
       [2, 3, 2, 4, 4, 3],
       [3, 1, 2, 2, 3, 4],
       [1, 1, 1, 4, 4, 4],
       [3, 3, 3, 2, 3, 1],
       [4, 3, 4, 2, 3, 2],
       [2, 1, 3, 3, 4, 3],
       [2, 3, 3, 2, 3, 4],
       [1, 1, 1, 1, 1, 1],
       [3, 5, 1, 4, 5, 5],
       [3, 3, 2, 2, 3, 1],
       [3, 2, 3, 2, 2, 3],
       [2, 1, 2, 3, 3, 2],
       [3, 2, 3, 3, 3, 3],
       [4, 4, 4, 3, 4, 4],
       [3, 3, 1, 4, 4, 3],
       [3, 2, 1, 1, 1, 1],
       [3, 1, 2, 3, 3, 3],
       [1, 1, 1, 2, 3, 3],
       [4, 3, 1, 1, 3, 3],
       [4, 3, 3, 2, 4, 2],
       [2, 2, 3, 2, 2, 4],
       [1, 1, 1, 4, 4, 1],
       [1, 4, 1, 3, 3, 3],
       [2, 2, 2, 4, 3, 4],
       [4, 4, 4, 3, 3, 4],
       [1, 1, 1, 3, 3, 3],
       [3, 3, 3, 3, 3, 3],
       [3, 4, 5, 5, 4, 5],
       [1, 1, 1, 4, 5, 5],
       [4, 4, 4, 3, 4, 4],
       [4, 4, 4, 3, 3, 2],
       [2, 3, 2, 3, 2, 3],
       [4, 3, 2, 2, 3, 3],
       [3, 2, 2, 5, 3, 5],
 

In [5]:
generate_roll_num = np.array(range(1,file.shape[0]+1))     # This code is used to generate Roll num of each student
new_generate_roll_num = generate_roll_num.reshape(300,1)   # This is to reshape the elements generated to file shape

In [6]:
new_data = np.hstack([new_generate_roll_num,file])         # To append roll number to each row i.e each student
new_data

array([[  1,   1,   1,   1,   1,   1,   1],
       [  2,   4,   4,   3,   4,   4,   4],
       [  3,   2,   1,   3,   4,   1,   1],
       [  4,   2,   3,   2,   4,   4,   3],
       [  5,   3,   1,   2,   2,   3,   4],
       [  6,   1,   1,   1,   4,   4,   4],
       [  7,   3,   3,   3,   2,   3,   1],
       [  8,   4,   3,   4,   2,   3,   2],
       [  9,   2,   1,   3,   3,   4,   3],
       [ 10,   2,   3,   3,   2,   3,   4],
       [ 11,   1,   1,   1,   1,   1,   1],
       [ 12,   3,   5,   1,   4,   5,   5],
       [ 13,   3,   3,   2,   2,   3,   1],
       [ 14,   3,   2,   3,   2,   2,   3],
       [ 15,   2,   1,   2,   3,   3,   2],
       [ 16,   3,   2,   3,   3,   3,   3],
       [ 17,   4,   4,   4,   3,   4,   4],
       [ 18,   3,   3,   1,   4,   4,   3],
       [ 19,   3,   2,   1,   1,   1,   1],
       [ 20,   3,   1,   2,   3,   3,   3],
       [ 21,   1,   1,   1,   2,   3,   3],
       [ 22,   4,   3,   1,   1,   3,   3],
       [ 23,   4,   3,   3,   2,

In [7]:
#Total number of students,total number of subjects
" ".join((str(new_data.shape[0]),str(new_data.shape[1]-1)))   # -1 since we have to remove Roll number column

'300 6'

In [8]:
#Max num of marks in each subject
#BIOLOGY #GEOLOGY #CHEMISTRY #ALGEBRA #CALCULUS #STATISTICS

np.max(new_data[:,1]),np.max(new_data[:,2]),np.max(new_data[:,3]),np.max(new_data[:,4]),np.max(new_data[:,5]),np.max(new_data[:,6])


(5, 5, 5, 5, 5, 5)

In [9]:
np.min(new_data[:,1]),np.min(new_data[:,2]),np.min(new_data[:,3]),np.min(new_data[:,4]),np.min(new_data[:,5]),np.max(new_data[:,6])

(1, 1, 1, 1, 1, 5)

In [10]:
# This is to calculate average(mean) of each subject and to find the subject haing maximum mean.
mean = np.array([np.mean(new_data[:,1]),np.mean(new_data[:,2]),np.mean(new_data[:,3]),np.mean(new_data[:,4]),np.mean(new_data[:,5]),np.mean(new_data[:,6])])
max_mean = np.max(mean)   
mean == max_mean         # This is to find which column(subject has max mean) or #np.where(mean == max_mean)

#The WINNER is CALCULUS!!!!!

array([False, False, False, False,  True, False])

In [24]:
sum_of_each_students_marks = np.sum(new_data[:,1:],axis=1)  # Gives sum of each students marks
highest_students_marks = np.max(sum_of_each_students_marks)  # Finds the maximum marks out of all student's total marks
result = np.where(sum_of_each_students_marks == highest_students_marks)  # searches who got the max marks(pos) in sum_of_each_student's array marks
for x in np.nditer(result):              # There can be more than one student who got the max marks so use for loop.. as it is numpy array use nd.iterator        
    x = x+1                              # Increment by 1 since.. roll number,index starts with 0 
    print(x)    
    
# In this data set there is only 1 top scorer and our 1st ranker is Roll number : 242 !!!! Partyyyy!!!!

242


In [25]:
from matplotlib import pyplot as plt